### ISSUE TITLE
project not being exported properly

### ISSUE THREAD

**Issue by dpassen** [aurtzy/disproject#2]
When I invoke "C-x p" `disproject-dispatch`, I can use "p" to select a project and it's visible in the transient menu. However, when I hit "f", I'm now prompted to select a project. AFAICT, this is new behavior.

My configuration:
```elisp
(use-package disproject
  :ensure t
  :custom
  (disproject-find-line-command #'consult-line-multi)
  (disproject-shell-command #'eat-project)
  (disproject-switch-to-buffer-command #'consult-project-buffer)
  :general (ctl-x-map "p" 'disproject-dispatch))
```

I believe this started when I upgraded both disproject and transient to their latest commits.

**Comment by aurtzy** [comment]
Thanks for the report! This appears to be caused by a recent Transient; I can't reproduce on Transient v0.7.8, but the latest commit does reveal this behavior... I'll have to investigate it further.

**Comment by aurtzy** [comment]
Just pushed a commit that should fix this; should end up in MELPA soon.

I'd like to keep this issue open for now since I'm still not sure if this was some kind of Disproject bug revealed by a Transient fix or an unintended behavior change in the function originally used.
