### ISSUE TITLE
disproject-compile doesn't respect customized 'compile-command'

### ISSUE THREAD

**Issue by dpassen** [aurtzy/disproject#3]
In a project with a .dir-locals file:
```emacs-lisp
((nil
  (compile-command . "foo")))
```
Selecting "c" from the disproject transient menu presents with:
```
Compile command: make -k 
```
where as running, `M-x project-compile` presents with:
```
Compile command: foo
```

I would expect `disproject-compile` to present the same option.

**Comment by aurtzy** [comment]
Yes, I would expect this as well. The issue should be fixed in 062438d65d6b6456268b105635a0a66447540c0d; thanks for the report!
